name: dotnet Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:     
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  # Adjust to the version you are using

    - name: Build and publish
      run: |
        cd sample-packages/dotnet/GitHubTest
        dotnet restore
        dotnet build --configuration Release
        dotnet pack --configuration Release --output nupkg

    - name: Publish to NuGet
      run: |
        dotnet nuget push sample-packages/dotnet/GitHubTest/nupkg/*.nupkg --api-key ${{ secrets.NUGET_PACKAGE_TOKEN }}  --source "github"
