name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:     
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          
      - name: Install dependencies
        run: npm install
        
      - name: Build and test
        run: npm --prefix=./sample-packages/npm/ run build
        
      - run: npm publish ./sample-packages/npm/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
